Module6 task2
htmlacademy-yii/2074903-task-force-4 pull request #13
Opened 2022-10-04 16:08 UTC by MariOlya

2022-10-07 21:24 UTC, selyatin83 commented on controllers/ProfileController.php
> +            $executorStatistic = new ExecutorStatistic($id);
Прямая зависимость, так лучше не делать.
Не обязательно переделывать, просто имей ввиду, что в коммерческом коде так делать не стоит

2022-10-07 21:45 UTC, selyatin83 requested changes

2022-10-07 21:45 UTC, selyatin83 commented on src/domain/traits/CountTime.php
> +trait CountTime
Классы, трейты, интерфейсы не должны быть глаголами(действиями), только им. существительное
К примеру, TimeCounter можешь назвать

2022-10-07 21:45 UTC, selyatin83 commented on src/domain/traits/CountTime.php
> +        $unixCreateAt = Yii::$app->formatter->asTimestamp($this->createAt);
Неправильно, у тебя внутренности метода трейта не должны на прямую зависеть от класса в который вставляется трейт. 
Тебе нужно передавать в параметры метода всю модель AR и из нее брать данные, или несколько аргументов

2022-10-07 21:45 UTC, selyatin83 commented on src/domain/traits/CountTime.php
> +        $unixCreateAt = Yii::$app->formatter->asTimestamp($this->createAt);
`$this->createAt`
Нужно передавать в параметрах метода

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +    }
Зачем передавать id и снова делать выборку?
Лучше сразу передавать уже выбранную модель AR пользователя

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +            ->where('tasks.status = 3')->all();
Эту выборку нужно вынести в бизнес модель или репозиторий (UserRepository) и обозвать метод его "функционалом".

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +        return $this->executor->getExecutorReviews()->count();
Выборку в методе getExecutorReviews можно закешировать на ~1 час.

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +            ->where('tasks.status = 5')->count();
Эта логика также должна быть в бизнес модели User или репозитории пользователя

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +            ->where('tasks.status = 4')->count();
Эта логика также должна быть в бизнес модели User или репозитории пользователя

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +            0;
Нарушение стандарта PSR-12
Установи себе код стайл в phpstorm

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +            0;
Очень сложно читается.
Ни пробелом, ни табов, ни переносов,  ни вынесено ничего в отдельные переменные для удобства чтения.

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +        return array_search($currentExecutorRating, $allRating) + 1;
Также PSR-12 поправить под стандарты

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +class ExecutorStatistic
Зачем тебе этот класс?
Ты можешь создать новую модель ExectorUser унаследовать от базовой Users модели, и добавить этот функционал в эту новую модель исполнителя

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +            0;
Поправить под стандарты PSR-12

2022-10-07 21:45 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +            0;
код стайл

2022-10-07 21:46 UTC, selyatin83 commented
На странице профиля пользователя что-то с версткой, где специализации и био
<img width="391" alt="image" src="https://user-images.githubusercontent.com/53401667/194665153-547ba6d2-dc94-4ddf-b6e1-44e0233f0bdc.png">

2022-10-08 00:31 UTC, MariOlya commented on src/domain/traits/CountTime.php
> +trait CountTime
да, я знаю, поэтому использовала count в значении существительного - "подсчет"/"количество"

2022-10-08 00:33 UTC, MariOlya commented on src/domain/traits/CountTime.php
> +        $unixCreateAt = Yii::$app->formatter->asTimestamp($this->createAt);
Как сказали коллеги, в таком случае будет какая-то более сложная реализация. ну типа в вызов модели надо будет передавать саму же модель.

2022-10-08 00:35 UTC, MariOlya commented on src/infrastructure/statistic/ExecutorStatistic.php
> +    }
Логично, спасибо, я об этом не подумала =) Спасибо

2022-10-08 00:36 UTC, MariOlya commented on src/infrastructure/statistic/ExecutorStatistic.php
> +            ->where('tasks.status = 3')->all();
С репозиторием - я только натыкалась и для этого мне надо будет осваивать новую тему самостоятельно - это потребует кучу времени, которого сейчас нет
В модель вынести думала (и даже выносила), но не работало (не из-за того, что вынесла, а из-за других ошибок), ничего не мешает попробовать вынести снова, конечно

2022-10-08 00:37 UTC, MariOlya commented on src/infrastructure/statistic/ExecutorStatistic.php
> +        return $this->executor->getExecutorReviews()->count();
Это я тоже не знаю как работает и придется осваивать(?), поэтому опять же доп время

2022-10-08 00:40 UTC, MariOlya commented on src/infrastructure/statistic/ExecutorStatistic.php
> +            0;
написано всё как обычно и писали по отдельности
вроде у меня и так стоит (и ничего не подчеркивалось), но я проверю

2022-10-08 00:41 UTC, MariOlya commented on src/infrastructure/statistic/ExecutorStatistic.php
> +class ExecutorStatistic
так я у тебя спрашивала нужен новый класс, ты сказал "да"

2022-10-08 01:00 UTC, MariOlya commented on src/infrastructure/statistic/ExecutorStatistic.php
> +            0;
Проверила, подключила. 
Он ничего не подчеркивает там, где ты говоришь.
конкретно в этом классе он не согласен только с тем, что у констант не указано паблик, что вообще-то странно для констант. а все остальное по правилам

2022-10-08 03:11 UTC, MariOlya commented on controllers/ProfileController.php
> +            $executorStatistic = new ExecutorStatistic($id);
Я не понимаю, как надо делать по-другому
Или это все еще про интерфейсы или приводи примеры, пожалуйста

2022-10-08 03:26 UTC, MariOlya commented on src/infrastructure/statistic/ExecutorStatistic.php
> +class ExecutorStatistic
дальше я просила - свой полностью и ты сказал "да"

2022-10-08 03:31 UTC, MariOlya commented on src/infrastructure/statistic/ExecutorStatistic.php
> +class ExecutorStatistic
в общем, я все равно не знаю, как работать с конструктором в унаследованном классе, куда мне надо передать модель основного. поэтому проще все перенести в модель users

2022-10-08 04:35 UTC, MariOlya commented on src/domain/traits/CountTime.php
> +trait CountTime
ладно, у меня нет времени спортить

2022-10-08 05:02 UTC, MariOlya commented on src/domain/traits/CountTime.php
> +        $unixCreateAt = Yii::$app->formatter->asTimestamp($this->createAt);
и здесь некогда спорить

2022-10-08 05:02 UTC, MariOlya commented on src/infrastructure/statistic/ExecutorStatistic.php
> +class ExecutorStatistic
или оставить так, как есть

2022-10-12 14:07 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +        return $this->executor->getExecutorReviews()->count();
Посмотри, как работает кеширование запросов в Yii2 у ActiveQuery, просто вызов метода ->cache у AQ

2022-10-12 14:08 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +class ExecutorStatistic
Скорей всего ты задаешь неправильные вопросы.

2022-10-12 14:09 UTC, selyatin83 commented on src/infrastructure/statistic/ExecutorStatistic.php
> +class ExecutorStatistic
Можешь перенести в модель Users, ок, но теоритечески скорей всего лучше разделить, т.к. Users общее понятие, а поведение будет для отдельной категории User`ов

2022-10-12 14:10 UTC, selyatin83 commented on controllers/ProfileController.php
> +            $executorStatistic = new ExecutorStatistic($id);
Тебе нужно разобраться с контейнером зависимостей в Yii2 и в общем его понятии

2022-10-12 14:13 UTC, selyatin83 commented on controllers/ProfileController.php
> +            $executorStatistic = new ExecutorStatistic($id);
Выдели себе время, и полностью разбери тему интерфейсов, контейнера зависимостей.
Запиши вопросы, которые непонятны, потом на созвоне обсудим

В кратце: этот класс нужно передать в аргументы метода интерфейс этого класса и установить на этот интерфейс зависимость, которая реализует этот интерфейс.
Но я бы начал с вопроса, а нужен ли тебе вообще этот класс, как по мне он лишний

2022-10-12 14:13 UTC, selyatin83 commented on controllers/ProfileController.php
> +            $executorStatistic = new ExecutorStatistic($id);
Для этого я бы использовал отдельную модель + сервис, этого достаточно

2022-10-14 01:03 UTC, merged