Module6 task3
htmlacademy-yii/2074903-task-force-4 pull request #14
Opened 2022-10-07 06:35 UTC by MariOlya

2022-10-07 21:59 UTC, selyatin83 requested changes

2022-10-07 21:59 UTC, selyatin83 commented on src/infrastructure/models/form/RegistrationForm.php
> +    }
У тебя форма занимается двумя задачами:
1. Валидацией
2. Создание пользователя
Это нарушение хороших практик, SOLID , принципа единственной ответственности, который говорит, о том, что любой класс, модуль, функция должна иметь одну причину для изменения( у тебя их сейчас 2 )

Создание пользователя давай вынесем в сервис или фабрику и в параметры методы создания будем передавать эту форму.

2022-10-07 22:00 UTC, selyatin83 commented
Что-то с шапкой + когда а зарегался, меня перебросило на гл. страницу, и кнопка регитрации и входа остались(в теории пользователя сразу нужно авторизовать я думаю после регистрации)
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/53401667/194668655-d29e99dd-b856-4094-a136-4869042ce105.png">

2022-10-08 04:18 UTC, MariOlya commented on src/infrastructure/models/form/RegistrationForm.php
> +    }
ни сервис ни фабрику мы не изучали на этом курсе
мне снова нужно будет осваивать что-то новое, это снова время

2022-10-08 04:19 UTC, MariOlya commented on src/infrastructure/models/form/RegistrationForm.php
> +    }
тем более в данном случае слишком много переменных, я даже себе представить не могу, как я могу их куда-то передать нормально

2022-10-08 06:07 UTC, MariOlya commented on src/infrastructure/models/form/RegistrationForm.php
> +    }
я пока перенесу это в контроллер, а потом обсудим

2022-10-12 14:16 UTC, selyatin83 commented on src/infrastructure/models/form/RegistrationForm.php
> +    }
Вы скорей всего не будете изучать это, вам дают только основу, а тебе говорю хорошие практики, как это делать более правильнее.
Конечно, ты можешь весь этот код записать чисто в контроллер и все будет работать, но спустя месяцы, годы, как проект будет равзиваться все опять упрется в поддержку кода, и твоя реализация будет рефакториться.

2022-10-12 17:40 UTC, selyatin83 requested changes

2022-10-12 17:40 UTC, selyatin83 commented on controllers/RegistrationController.php
> +                $newUser->attributes = $_POST['RegistrationForm'];
Почему используешь суперглобальный массив пост?
Нужно использовать компоненты фреймворка

2022-10-12 17:40 UTC, selyatin83 commented on controllers/RegistrationController.php
> +        $newUser = new Users();
Создание и заполнение пользователя нужно вынести из контроллера, это не его задача

2022-10-12 17:40 UTC, selyatin83 commented on controllers/RegistrationController.php
> +                $newUser->save(false);
На этот метод нужно try catch , иначе приложение упадет

2022-10-12 17:40 UTC, selyatin83 commented on controllers/RegistrationController.php
> +                $newUser->attributes = $_POST['RegistrationForm'];
Речь про Yii::$app->request->post()

2022-10-12 17:41 UTC, selyatin83 commented on controllers/RegistrationController.php
> +                $newUser->save(false);
Еще подумай над тем, что показывать, если пользователь не создался, т.е. метод save вернул false или кинул исключение

2022-10-13 10:25 UTC, MariOlya commented on controllers/RegistrationController.php
> +                $newUser->attributes = $_POST['RegistrationForm'];
просто у нас не было инструкции как записывать все safe параметры разом, а референс нашла только такой

2022-10-13 10:26 UTC, MariOlya commented on controllers/RegistrationController.php
> +        $newUser = new Users();
Да я знаю, но мы же обсудили, что пока я это положу туда, а потом мы пройдемся по контроллерам и обсудим в сервис или в интерфейс что надо вынести. мы же только вчера договорились!

2022-10-13 10:27 UTC, MariOlya commented on controllers/RegistrationController.php
> +                $newUser->save(false);
на save надо try-catch?

2022-10-13 10:38 UTC, MariOlya commented on controllers/RegistrationController.php
> +                $newUser->attributes = $_POST['RegistrationForm'];
всё, по этому нашла информацию

2022-10-13 11:13 UTC, MariOlya commented on controllers/RegistrationController.php
> +                $newUser->save(false);
подожди, тут же не прям в контроллере должно быть try catch, а кидать тут exception, правильно?

2022-10-13 11:54 UTC, MariOlya commented on controllers/RegistrationController.php
> +        $newUser = new Users();
хотя, если ты предлагаешь это записать отдельным методом activeRecord, то согласна, но маякни так или не так

2022-10-14 01:13 UTC, merged