Module7 task2
htmlacademy-yii/2074903-task-force-4 pull request #16
Opened 2022-10-11 15:55 UTC by MariOlya

2022-10-20 06:55 UTC, selyatin83 commented on controllers/TasksController.php
> +                'model' => $TaskFilterForm,
наименование переменных с большой быквы обычно не делают

2022-10-20 06:56 UTC, selyatin83 commented on controllers/TasksController.php
> +            $newTask = new ServiceTaskCreate($createTaskForm);
Прямая зависимость, в проде такое бы не одобрили

2022-10-20 06:58 UTC, selyatin83 commented on controllers/TasksController.php
> +            $newTask = new ServiceTaskCreate($createTaskForm);
наименование переменной newTask не подходит к тому, что в ней лежит. Как минимум: taskService или serviceTaskCreator

2022-10-20 06:59 UTC, selyatin83 commented on src/application/services/task/create/ServiceTaskCreate.php
> +    public function saveMainContent() : void
Это название метода меня запутало, я считаю, что оно не подходит к тому, что в нем происходит

2022-10-20 07:11 UTC, selyatin83 requested changes

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/task/create/ServiceTaskCreate.php
> +        $this->newTask->clientId = Yii::$app->user->identity->id;
Эти данные уже ДОЛЖНЫ приходить валидными в аргумента метода, получать из глобального состояния их здесь нельзя, это критичная ошибка

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/task/create/ServiceTaskCreate.php
> +        $this->newTask->status = TaskStatuses::findOne(['taskStatus' => 'new'])->id;
Также здесь - уже приходит валиднео состояние, поисков быть недолжно

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/task/create/ServiceTaskCreate.php
> +    public function saveMainContent() : void
Этот метод должен ТОЛЬКО создавать, никаких других действий не должен делать: получил данные - вставил - создал

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/task/create/ServiceTaskCreate.php
> +        if (!Tasks::findOne($this->newTask->id)) {
Это лишнее, т.к. save тебе вернет true или false или кинет исключение

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/task/create/ServiceTaskCreate.php
> +    public function saveFile(UploadedFile $file) : void
Сервис относится к создание задачи, а в нем лежат методы по работе с другими моделями и логикой, это не правильно, получается уже не сервис а склад любой логики, которой захочешь

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/task/create/ServiceTaskCreate.php
> +        if (!Files::findOne($this->newFile->id)) {
Лишнее также

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/task/create/ServiceTaskCreate.php
> +    public function getIdNewTask() : int
У тебя сервис не должен хранить состояние

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/task/create/ServiceTaskCreate.php
> +    public function getIdNewTask() : int
В лучшем случае должно быть так: Сервис имеет методы с аргументам, при необходимости в состоянии сервиса могут лежать другие зависимости из di, сервисы, репозитории, в методах уже происходит какая-то логика и отдается ответ

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/user/create/ServiceUserCreate.php
> +        $newUser->attributes = Yii::$app->request->post('RegistrationForm');
получение данных из глобального массива - критическая ошибка. Эти данные уже должны поступать в аргументах и ВАЛИДНЫМИ. До этого метода никогда не должны доходить невалидные данные или пустые если они обязательны

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/user/create/ServiceUserCreate.php
> +        if (!Users::findOne($newUser->id)) {
Также лишнее

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/user/show/ServiceProfileShow.php
> +    public static function getUserProfile($id) : Users
Здесь лучше назвать метод getUserExecuterById

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/user/show/ServiceProfileShow.php
> +    public static function getUserProfile($id) : Users
к примеру

2022-10-20 07:11 UTC, selyatin83 commented on src/application/services/user/show/ServiceProfileShow.php
> +            throw new NotFoundHttpException('Task is not found', 404);
Название ошибки неправильно вроде, не task а users

2022-10-20 14:07 UTC, MariOlya commented on src/application/services/task/create/ServiceTaskCreate.php
> +        if (!Tasks::findOne($this->newTask->id)) {
ты сам мне сказал это проверять, если не сохранилось

2022-10-21 06:18 UTC, selyatin83 commented on controllers/ProfileController.php
> +                $userProfile = ServiceUserShow::getUserExecutorById($id);
Сервис можно просто навзать ServiceUser тогда

2022-10-21 06:20 UTC, selyatin83 commented on controllers/TasksController.php
> +    public function actionCreate() : string|Response
В этот метод желательно в будущем добавить транзакцию, как минимум на сохранение файлов

2022-10-21 06:21 UTC, selyatin83 commented on controllers/TasksController.php
> +    public function actionCreate() : string|Response
и связей

2022-10-21 06:23 UTC, selyatin83 commented on src/application/services/file/save/ServiceFileSave.php
> +        if (!$savedFile->save(false)) {
Вообще я думаю, что при сохранении файлов не нужно "ронять" приложение.
На будущее: Такие неважные, и многочисленные сохранения обычно грузят асинхронно, т.е. используют очереди

Не нужно переделывать, просто знай

2022-10-21 06:25 UTC, selyatin83 commented on src/application/services/task/create/ServiceTaskCreate.php
> +class ServiceTaskCreate
Глаголы в названиях класса. 
Тогда creater используй, saver и т.п.

2022-10-21 06:27 UTC, selyatin83 commented on src/application/services/user/create/ServiceUserCreate.php
> +        if (!$createdUser->save(false)) {
Сохранение должно быть только 1 раз.

2022-10-21 06:27 UTC, selyatin83 commented on src/application/services/file/save/ServiceFileTaskRelations.php
> +        if (!$taskFile->save(false)) {
Также, только 1 раз

2022-10-21 06:27 UTC, selyatin83 commented on src/application/services/file/save/ServiceFileSave.php
> +        if (!$savedFile->save(false)) {
Также, только 1 раз сохранять нужно

2022-10-21 06:29 UTC, selyatin83 commented on controllers/TasksController.php
> +    public function actionCreate() : string|Response
Не нужно переделывать, просто знай

2022-10-21 06:30 UTC, merged