Module1 task2
htmlacademy-yii/2074903-task-force-4 pull request #2
Opened 2022-08-14 15:29 UTC by MariOlya

2022-08-15 21:42 UTC, selyatin83 requested changes
Не увидел реализацию метода из ТЗ:

> класс имеет метод для получения доступных действий для указанного статуса

2022-08-15 21:42 UTC, selyatin83 commented on classes/TaskStatusAndActionsIndicator.php
> +class TaskStatusAndActionsIndicator
Название класса не должно быть из and/or, класс должен выполнять одну задачу, предлагаю назвать просто Task, по ходу прохождения курса класс будем рефакторить и приводить его к правильной архитектуре

2022-08-15 21:42 UTC, selyatin83 commented on classes/TaskStatusAndActionsIndicator.php
> +    public $currentAction = '';
Давай придерживаться идеи, что указываем всегда типы данных, и лучше всего использовать конструкцию declare(strict_types=1); , будет время почитай о ней

2022-08-15 21:42 UTC, selyatin83 commented on tests/check-status-indicator.php
> +require_once '../classes/TaskStatusAndActionsIndicator.php';
Рекомендую использовать константу __DIR__ для работы с путями.

Можно сделать примерно такое: 
`
$root = __DIR__ . '/../';
$file = $root . "/classes/TaskStatusAndActionsIndicator.php";
`

2022-08-15 21:42 UTC, selyatin83 commented on tests/check-status-indicator.php
> +require_once '../classes/TaskStatusAndActionsIndicator.php';
__DIR__ - это магическая константа
подробнее https://www.php.net/manual/ru/language.constants.magic.php

2022-08-15 21:42 UTC, selyatin83 commented on classes/TaskStatusAndActionsIndicator.php
> +        if ($this->currentAction) {
Передача action`а задания есть только в конструторе или на прямую через вызов свойства объекта.

Предлагаю переименовать метод, к примеру, toAction или changeStatusByAction, установить у данного метода параметр $action(действие), который нам будет передавать клиентский код, чтобы изменить статус задания, далее сверять что данное действие существует и допустимо для текущего статуса, и переводить в новый статус, если все условия выполняются, после также отдавать(возвращать) новый статус.

Также давай сделаем currentStatus и currentAction приватными свойствами, т.к. клиентам незачем знать внутренности объекта, а будут работать с ними через доступный интерфейс(методы) объекта.
Чтобы можно было получать значения приватных свойств объекта, существует методы геттеры, они просто возвращают значение свойства.
`public function getCurrentStatus(): string 
{
 return $this->currentStatus; 
}`

Под клиентами я подразумеваю методы, и др. классы словя ниже, которые будут использовать этот класс.

2022-08-15 21:44 UTC, selyatin83 commented on tests/check-status-indicator.php
> +require_once '../classes/TaskStatusAndActionsIndicator.php';
У меня кстати не запустился код в этом файле, require не отработал, выдал ошибку, что файл был не найден, переделал на DIR и все отработало

2022-08-16 04:43 UTC, selyatin83 commented
> Не увидел реализацию метода из ТЗ:

Не заметил деталь в методе getAvailableActions, это замечание можно скипать

2022-08-17 21:34 UTC, selyatin83 requested changes

2022-08-17 21:34 UTC, selyatin83 commented on classes/Task.php
> +        if (in_array($currentAction, $availableActions)) {
На строчке 58 у меня падает ошибка, т.к. ключа $this->currentStatus не существует в массиве, который возвращает getAvailableActions. У тебя там всего 2 ключа forClients и forExecutre, неверная логика, нужно подправить, чтобы проверка была по ключам action`ам

2022-08-17 21:34 UTC, selyatin83 commented on classes/Task.php
> +        if (in_array($currentAction, $availableActions)) {
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/53401667/185247091-3c884db3-7aba-4a5e-8831-478ea1a0c8e3.png">

2022-08-18 03:01 UTC, MariOlya commented on classes/Task.php
> +        if (in_array($currentAction, $availableActions)) {
Да, это именно та ошибка, которую я нашла и исправила благодаря phpunit. Я пытаюсь здесь искать значение в массиве, а надо искать ключ в массиве. Уже исправлено к следующей задаче

2022-08-18 06:09 UTC, selyatin83 commented
Договорились, что эта ошибка будет поправлена в 3ем задании

2022-08-18 06:09 UTC, merged