Ну вот и всё
htmlacademy-yii/2074903-task-force-4 pull request #20
Opened 2022-10-31 18:29 UTC by MariOlya

---
:mortar_board: [Ну вот и всё](https://up.htmlacademy.ru/yii/4/user/2074903/tasks/19)

2022-11-05 21:14 UTC, selyatin83 requested changes

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/file/parse/ServiceFileParse.php
> +            return '/uploads/avatars/' . $name;
Здесь направшивается константа или конфиг в приложении на дефолтный путь аватаров в хранилище

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/respond/RespondCreateService.php
> +    public function saveNewRespond(NewRespondDto $dto): void
Обычно такие методы фабрики должны возвращать созданную модель/сущность

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/respond/dto/NewRespondDto.php
> +    }
Рекомендация, если ты не знала о таком
В IDE PhpStorm есть создание конструкторов, геттеров, сеттеров, имплементируемые методы интерфейсом с помощью быстрых клавиш.
Как только ты написала свойства класса, к примеру, нажимаешь(на маке) command+N , и выбираешь то что тебе нужно, я этим пользуюсь и очень сильно ускоряет разработку. Не забывай про быстрое выделение с помощью шифта нескольких строк и более

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/respond/interfaces/RespondStatusAddInterface.php
> +    public function addRestRespondsRefuseStatus(array $responds, ?Responds $acceptedRespond = null);
Рекомендации: В коммерческом коде я всегда описываю минимальный набор PHP Docs для класса, методов, свойств.

У класса: Автора, и краткий комментарий при необходимости
У свойств их типизацию, краткий комментарий при необходимости
У методов параметры, возвращаемые значения, краткие комментарии при необходимости, также здесь им указываем в ком. коде deprecated, если он устарел и краткий коммент о том, что использовать взамен этому методу если есть замена.

По кратким комментариям: Не увлекайся, т.к. ты должна стремиться писать код так, чтобы комментарии были не нужны, но если бизнес логика сложная или что-то запутанное лучше это прокоментировать.

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/task/filter/ServiceTaskFilter.php
> +    public static function filterClientTasks(int $clientId, ?int $status = null) : array
Метод фильтрует задачи только по статусу, а читая название метода я ожидаю глобальную фильтрацию по любому из доступных атрибутов модели.

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/task/filter/ServiceTaskFilter.php
> +    public static function filterClientTasks(int $clientId, ?int $status = null) : array
Переделывать необязательно, просто взгляд со стороны

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/task/filter/ServiceTaskFilter.php
> +        return $allClientTasks->andWhere(['status' => $status])->all();
```
return Tasks::find()->where(['clientId' => $clientId])
    ->andWhere(['status' => $status ?? TaskStatusConstants::ID_NEW_STATUS])
    ->all();
```

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/task/filter/ServiceTaskFilter.php
> +        return $allClientTasks->andWhere(['status' => $status])->all();
К примеру, можно так улучшить читаемость кода

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/task/filter/ServiceTaskFilter.php
> +        return $allExecutorTasks->andWhere(['status' => $status])->all();
По комментарию выше ожидаю, что попробуешь также улучшить структуру кода здесь

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/user/addData/ServiceUserCategoriesAdd.php
> +                        $newExecutorCategory->categoryId = (int)$categoryId;
А если id категории не существует такой? Как поведет себя в этом случае транзакция? Упадет вся или только одна запись не сохранится?

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/user/addData/ServiceUserCategoriesAdd.php
> +                        $newExecutorCategory->categoryId = (int)$categoryId;
И прокинется ли исключение о том, что упало сохранение выше по коду и узнает ли об этом клиенты?
Если кажется вопрос сложный, можешь скипнуть

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/user/addData/ServiceUserCategoriesAdd.php
> +                        $newExecutorCategory->categoryId = (int)$categoryId;
Я использовал другую структуру транзакции обычно, и не знаю поведение это через анонимную функцию

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/user/addData/ServiceUserCategoriesAdd.php
> +    public static function saveExecutorCategories(Users $user, ?array $categories = null) : void
Функция статичная, но не идемпотентная, т.к. при каждом ее вызове состояние будет изменяться. 
Необязательно править, просто комментарий со стороны

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/user/addData/ServiceUserDataAdd.php
> +    public static function addUserVkId(Users $user, array $attributes) : void
Какова роль этого метода? У модели пользователя уже есть интерфейс addVkId
Вижу, как интерфейс для интерфейса

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/user/addData/ServiceUserDataAdd.php
> +    public static function updateUserProfile(Users $user, EditProfileForm $form, ?string $avatarSrc = null) : void
Та же ситуация, что и с addUserVkId, обертка над оберткой, а какую проблему решаем этим?

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/user/addData/ServiceUserDataAdd.php
> +    public static function updateUserPassword(SecurityProfileForm $form, Users $user) : void
Та же ситуация, что и с addUserVkId, обертка над оберткой, а какую проблему решаем этим?

2022-11-05 21:14 UTC, selyatin83 commented on src/application/services/user/addData/ServiceUserDataAdd.php
> +class ServiceUserDataAdd
Судя по методам сервиса выглядит, как будто он бесполезный

2022-11-05 21:14 UTC, selyatin83 commented on src/domain/models/user/Users.php
> +                $this->phone = $correctPhone;
Валидацию номера телефона нужно вынести на уровень инфраструктуры, я его делаю обычно через Value Object

2022-11-05 21:14 UTC, selyatin83 commented on src/domain/models/user/Users.php
> +    public function deleteAllExecutorCategories() : void
Выглядит странным решением, отпиши, пожалуйста, почему решила его сделать

2022-11-05 21:14 UTC, selyatin83 commented on src/infrastructure/models/form/SecurityProfileForm.php
> +                $this->addError($attribute, 'Неправильный пароль');
Ошибка с текстом "неправильный пароль" будет и в случае отстутвия пользователя. Логика выдачи ошибок немного неправильная

2022-11-05 21:16 UTC, selyatin83 commented
Еще я допустил ошибку и упустил важный момент.
Это не относится конкретно к этому заданию и уже, конечно, поздно, но важно чтобы ты понимала это

Как ты собираешься отслеживать работоспособность приложения? Клиентское поведение, и т.п.?

2022-11-05 21:18 UTC, selyatin83 commented on src/domain/models/user/Users.php
> +                $this->phone = $correctPhone;
или вынеси это в форму

2022-11-06 05:10 UTC, MariOlya commented on src/application/services/respond/RespondCreateService.php
> +    public function saveNewRespond(NewRespondDto $dto): void
Да, но потом ты сказал, что не всегда, не надо везде типа пихать это возвращение. Если оно не требуется, то может и не возвращать

2022-11-06 05:24 UTC, MariOlya commented on src/application/services/user/addData/ServiceUserDataAdd.php
> +    public static function updateUserProfile(Users $user, EditProfileForm $form, ?string $avatarSrc = null) : void
ну мы это с тобой обсуждали, когда ты вообще говорил, что стоит это в модели переносить. и пришли к выводу, что модель выполняет конкретное действие, но не бросает исключение, это делает сервис - это раз. два - так контроллер меньше знает о том, что там происходит в модели, у него просто свой сервис. три - здесь (в сервисе) могли бы / могут быть дополнительные проверки бизнес логики. в модели проверок нет в этих методах, они просто выполняют обновление записи

2022-11-06 05:27 UTC, MariOlya commented on src/domain/models/user/Users.php
> +    public function deleteAllExecutorCategories() : void
потому что у нас в базе сохранены старые категории исполнителя. потом он заходит в форму и вместо категорий 1,3,5 выбирает 2,4,6 - как поступить с тем, что у нас уже отмечены в БД 1,3,5? Если их не удалять, то выйдет, что человек работает в категориях 1,2,3,4,5,6 - а он там не работает. Он категории поменял.
Или я не понимаю твой вопрос

2022-11-06 19:19 UTC, selyatin83 commented on src/domain/models/user/Users.php
> +    public function deleteAllExecutorCategories() : void
Решили не переделывать

2022-11-07 05:13 UTC, MariOlya commented on src/application/services/user/addData/ServiceUserCategoriesAdd.php
> +                        $newExecutorCategory->categoryId = (int)$categoryId;
Обсудили, решено без исправлений

2022-11-07 23:39 UTC, selyatin83 commented on controllers/TaskActionsController.php
> +            error_log('Error: '.$e->getMessage() . PHP_EOL, 3, Yii::getAlias('@webroot') . '/runtime/errors.log');
У Yii2 есть свой механизм логирования
https://www.yiiframework.com/doc/guide/2.0/ru/runtime-logging

2022-11-08 15:31 UTC, merged