Module3 task1
htmlacademy-yii/2074903-task-force-4 pull request #6
Opened 2022-08-30 03:40 UTC by MariOlya

2022-09-01 21:42 UTC, selyatin83 requested changes
Также не увидел проверку валидности параметров у объектов-значений действий
AcceptAction, CancelAction и т.п.
Как минимум ожидаю, что в методах isAvailableForUser будет проверка на то что переданные int значения > 0, иначе кидать исключения о не валидности данных

И вообще давай переделаем action`ы немного, вынесем int $idUser, int $idClient, int $idExecutor в свойства класса, и будем заполнять их из конструтора, и там же сделаем проверку на валидацию параметров > 0, иначе кинем исключение, а метод isAvailableForUser уже будет работать с приватным состоянием объекта(полями), тем самым мы соблюдем правила инкапсулирования данных, их приватности, и агрегируем валидацию передаваемых данных для валидного состояния объекта в одном методе, а именно в его конструкторе.

Если есть, что обсудить или есть аргументы, почему мои решения не нужны, готов созвонится

2022-09-01 21:42 UTC, selyatin83 commented on src/exception/CurrentActionException.php
> +        parent::__construct('Вам недоступно данное действие, выберите из предложенных', 0, null);
Почему решила захардкодить значения текста?
Почему решила переопределить конструктор в дечернем классе?

2022-09-01 21:42 UTC, selyatin83 commented on init.php
> +} catch (PDOException $dbError) {
В данном случае если ловишь какое-то конкретное исключение, то нужен еще дополнительный перехват "неожиданного" исключения, т.к. ты не уверена, что здесь только PDOException может вернуться.
Тебе нужно сделать еще один catch и ловить \Throwable исключение, так ты себя обезопасишь от неожиданного исключения, и падение программы.

Иначе просто лови любое исключение и завершай программу.
ВСЕГДА когда, ты не уверена, что может прелететь иное исключение, нужен дополнительный перехват таких исключений

2022-09-01 21:42 UTC, selyatin83 commented on init.php
> +} catch (PDOException $dbError) {
Переменная названа не совсем правильно.
По логике состоянием в переменной будет объект типа "Исключения", а не сама ошибка базы.
Принято называть такие переменные $e или $exception

2022-09-01 21:42 UTC, selyatin83 commented on src/domain/Task.php
> +            throw new CurrentActionException;
Текст ошибки я все таки вынес на уровень пользователя, а не инкапсулировал бы их в классе исключения + код ошибки пользовательский передать нельзя, т.к. ты хардкодишь его 0 в самом классе исключения, что уже урезает изначальный функционал исключений

2022-09-01 21:42 UTC, selyatin83 commented on src/exception/CurrentActionException.php
> +        parent::__construct('Вам недоступно данное действие, выберите из предложенных', 0, null);
Не видел никогда такие реализации за свой опыт
Вижу в таком случае минусы в управлении текстом ошибки и кодом ошибки.

Жду аргументов в пользу такого решения, иначе нужно будет переделать.

2022-09-01 21:42 UTC, selyatin83 commented on tests/TaskTest.php
> +        }
В тестировании нет смысла оборачивать в try catch.
Есть специальный метод у теста, который ожидает исключения конкретного типа, и если оно пришло с переданными параметрами, значит тест прошел успешно.

2022-09-02 13:15 UTC, MariOlya commented on src/exception/CurrentActionException.php
> +        parent::__construct('Вам недоступно данное действие, выберите из предложенных', 0, null);
В дочернем - потому, что в одной из статей, которые давали на обучении, было сказано, что свои ошибки лучше делать в своих классах, чтобы не выбрасывало в общем экспешене и было проще отделить одно от другого. Текст ошибки захардожен по той же причине - если у нас специальный класс для специального эксепшена, то а) он отвечает за конкретный текст ошибки, б) может использоваться в разных местах кода для одной и той же ошибки, и мы не должны писать каждый раз текст, как магическое значение. Оно должно быть в одном месте и управляемо / изменяемо в одной точке входа, а не разбросано там и сям

2022-09-02 13:17 UTC, MariOlya commented on init.php
> +} catch (PDOException $dbError) {
да, я уже поняла по названиям переменных, исправлю
про перехват любого исключения - спасибо, когда писала тут, мы еще их не изучали, и я не знала, как работают, а потом забыла исправить

2022-09-02 13:18 UTC, MariOlya commented on src/domain/Task.php
> +            throw new CurrentActionException;
это наше исключение, код ошибки нужен будет в общем исключении, которое ловится ниже

2022-09-02 13:19 UTC, MariOlya commented on tests/TaskTest.php
> +        }
не нашла такой реализации, дай ссылку
p.s. в любом случае, так тоже работает корректно

2022-09-05 21:58 UTC, merged